apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
    addonmanager.kubernetes.io/mode: Reconcile
  name: kube-system
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    k8s-app: istio
    addonmanager.kubernetes.io/mode: Reconcile
    app: istio-sidecar-injector
    chart: sidecarInjectorWebhook-1.0.3
    release: istio
    heritage: Tiller
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istio-sidecar-injector
        namespace: istio-system
        path: "/inject"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: istio-injection
        operator: NotIn
        values:
        - disabled

